tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "bat"
brew "coreutils"
brew "diff-so-fancy"
brew "exa"
brew "findutils", args: ["with-default-names"]
brew "fish"
brew "fzf"
brew "git"
brew "gnu-sed", args: ["with-default-names"]
brew "gnupg"
brew "go"
brew "grep", args: ["with-default-names"]
brew "hub"
brew "jabba"
brew "less"
brew "mas"
brew "moreutils"
brew "n"
brew "nano"
brew "neovim"
brew "openssh"
brew "python"
brew "screen"
brew "tig"
brew "tldr"
brew "tmux"
brew "vim", args: ["with-override-system-vi"]
brew "yadm"
brew "yarn"
cask "1password"
cask "adobe-creative-cloud"
cask "alfred"
cask "bartender"
cask "battle-net"
cask "bitbar"
cask "chrome-remote-desktop-host"
cask "discord"
cask "firefox"
cask "flux"
cask "font-fira-code"
cask "font-fira-sans"
cask "gitkraken"
cask "gitup"
cask "google-backup-and-sync"
cask "google-chrome"
cask "hyper"
cask "iina"
cask "iterm2"
cask "jetbrains-toolbox"
cask "kap"
cask "karabiner-elements"
cask "keybase"
cask "mullvadvpn"
cask "rocket"
cask "sketch"
cask "spotify"
cask "vagrant"
cask "virtualbox"
cask "visual-studio-code"
mas "AutoMute", id: 1118136179
mas "BetterSnapTool", id: 417375580
mas "Sip", id: 507257563
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
